FROM node:18 AS build

WORKDIR /app

COPY . .
RUN npm install

RUN npm run build --configuration=production

FROM nginx:alpine

# Elimina el index.html de nginx por defecto:
RUN rm -rf /usr/share/nginx/html/*

# Copia TU build completo:
COPY --from=build /app/dist/armario-virtual/browser/ /usr/share/nginx/html/

# Sobrescribe config:
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

